spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_bookstore
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: secret
  expiration-time: 864000000
